name: Package the pull requests for Retail

on:
  pull_request:
    branches:
      - master
      - develop
      - release/*
      - hotfix/*
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v2
      
      - name: Create the Retail package
        uses: BigWigsMods/packager@master
        with:
          args: -d -z
      
      - name: Upload the package as artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: SylingTracker-retail-pr${{ github.event.number }}
          path: .release/

